# **************************************************************************
# *
# * Authors:     Scipion Team (scipion@cnb.csic.es) [1]
# *
# * [1] Centro Nacional de Biotecnologia, CSIC, Spain
# *
# * This program is free software; you can redistribute it and/or modify
# * it under the terms of the GNU General Public License as published by
# * the Free Software Foundation; either version 3 of the License, or
# * (at your option) any later version.
# *
# * This program is distributed in the hope that it will be useful,
# * but WITHOUT ANY WARRANTY; without even the implied warranty of
# * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# * GNU General Public License for more details.
# *
# * You should have received a copy of the GNU General Public License
# * along with this program; if not, write to the Free Software
# * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA
# * 02111-1307  USA
# *
# *  All comments concerning this program package may be sent to the
# *  e-mail address 'scipion@cnb.csic.es'
# *
# *****************************************************************************
import logging
import traceback
from collections import Counter
from os.path import exists
import pyworkflow.protocol.params as params
from pwem.convert.headers import setMRCSamplingRate
from pyworkflow.protocol import STEPS_PARALLEL, ProtStreamingBase
from pyworkflow.utils import Message, cyanStr, redStr
from pyworkflow.utils.retry_streaming import retry_on_sqlite_lock
from tomo.objects import SetOfTiltSeries, TiltSeries, TiltImage
from imod.protocols import ProtImodBase
from imod.constants import OUTPUT_TILTSERIES_NAME, ODD, EVEN, MOD_EXT, CCDERASER_PROGRAM

logger = logging.getLogger(__name__)


class ProtImodXraysEraser(ProtImodBase, ProtStreamingBase):
    """
    Removes X-ray and detector-related spike artifacts from aligned tilt-series
    using the IMOD CCD eraser procedure. The protocol is designed to improve
    the visual and analytical quality of cryo-electron tomography data by
    identifying and correcting abnormal high-intensity pixels that typically
    arise from detector defects, cosmic rays, or transient acquisition artifacts.
    More info:
            https://bio3d.colorado.edu/imod/doc/man/ccderaser.html

    AI Generated:

    X-rays Eraser (ProtImodXraysEraser) — User Manual
        Overview

        The X-rays Eraser protocol removes bright spike artifacts from aligned
        tilt-series using the IMOD ccderaser methodology. These artifacts are
        commonly generated by X-rays, hot pixels, detector instabilities, or
        transient electronic events during image acquisition. Although often
        sparse, such defects can strongly interfere with downstream tomographic
        processing steps including alignment refinement, CTF estimation,
        denoising, reconstruction, segmentation, and subtomogram analysis.

        In cryo-electron tomography workflows, artifact removal is particularly
        important because tomographic reconstruction integrates information from
        many tilted projections. A single strong outlier pixel may propagate
        through reconstruction and generate streaks or localized distortions in
        the final tomogram. By correcting these abnormal peaks before later
        processing stages, the protocol improves reconstruction consistency and
        reduces the probability of introducing non-biological features into the
        reconstructed volume.

        Inputs and General Workflow

        The protocol operates on aligned tilt-series and processes each series
        independently. It is designed for streaming environments and can analyze
        incoming datasets progressively as acquisition or preprocessing
        continues. This behavior is especially useful in automated cryo-ET
        pipelines or facility-scale processing environments where large numbers
        of tilt-series are generated continuously.

        During processing, the protocol evaluates local image statistics in
        order to identify pixels or regions whose intensity patterns differ
        significantly from their surroundings. Detected artifacts are then
        replaced using local image information so that the corrected regions
        blend naturally with neighboring signal while preserving biologically
        meaningful structures.

        Biological users should understand that the protocol is intended to
        remove isolated acquisition artifacts rather than true structural
        features. Proper parameter selection is therefore important to avoid
        excessive correction in datasets containing naturally bright densities,
        fiducial gold particles, crystalline contaminants, or strongly
        scattering regions.

        Peak and Difference Detection Criteria

        Two of the most important parameters control how aggressively the
        protocol identifies abnormal peaks. The peak criterion determines how
        extreme an intensity value must be relative to the local mean before it
        is considered suspicious. Higher values produce conservative cleaning,
        while lower values increase sensitivity but may risk modifying valid
        signal.

        The difference criterion evaluates abrupt pixel-to-pixel changes. This
        parameter is especially useful for detecting sharp spike artifacts that
        differ strongly from surrounding pixels. In low-noise datasets, smaller
        thresholds may improve artifact detection, whereas noisier datasets may
        require more conservative values to avoid overcorrection.

        From a biological perspective, conservative settings are generally safer
        during exploratory processing because they preserve more original image
        information. Aggressive cleaning strategies should be applied carefully
        and visually validated, particularly in datasets containing fiducials or
        dense high-contrast structures.

        Artifact Size and Large Peak Detection

        The maximum radius parameter controls the approximate size of regions
        eligible for correction. This setting determines how broadly the
        algorithm expands around detected peaks. Small values focus correction
        on isolated defects, whereas larger values permit removal of broader
        artifact regions.

        Additional controls are available for handling exceptionally strong or
        large peaks. These settings help distinguish true detector artifacts
        from biologically meaningful dense regions or fiducial markers. In
        cryo-ET datasets containing gold fiducials, users should exercise
        caution because overly permissive artifact detection may partially alter
        fiducial appearance and negatively influence alignment quality.

        In practice, datasets acquired with modern direct electron detectors
        often require only mild correction, while older detectors or damaged
        acquisition frames may benefit from stronger cleaning parameters.

        Odd and Even Tilt-Series Processing

        The protocol can optionally process odd and even image subsets
        independently. This capability is particularly valuable in workflows
        involving noise estimation, resolution validation, denoising strategies,
        or subtomogram averaging procedures that rely on independent half-data
        separation.

        Maintaining separate corrected odd and even datasets allows later
        processing stages to preserve statistical independence while still
        benefiting from artifact removal. This is especially important in
        high-resolution workflows where improper handling of correlated noise
        could bias resolution estimation.

        Outputs and Their Interpretation

        The protocol generates corrected tilt-series in which X-ray and detector
        spike artifacts have been reduced or removed. The outputs preserve the
        geometry, acquisition metadata, and structural information of the
        original aligned tilt-series while providing cleaner image data for
        downstream processing.

        Biologically, the corrected datasets should exhibit fewer isolated bright
        spikes and reduced reconstruction streaking artifacts. However, users
        should visually inspect representative projections after processing to
        confirm that genuine structural features and fiducial markers remain
        intact.

        Practical Recommendations

        For most cryo-ET datasets, the default parameters provide a reasonable
        starting point and are usually sufficient for routine cleaning. When
        artifacts remain visible after processing, gradually increasing the
        sensitivity of the peak or difference criteria may improve results.

        In datasets containing abundant fiducial gold particles, users should
        avoid overly aggressive settings because strong filtering may distort
        fiducial appearance and interfere with alignment refinement. Visual
        validation of corrected projections is strongly recommended before
        proceeding to tomogram reconstruction.

        Streaming workflows particularly benefit from this protocol because
        artifact correction can be applied automatically as new tilt-series
        become available, reducing the need for later manual intervention and
        improving consistency across large acquisition campaigns.

        Final Perspective

        X-ray artifact removal is an important quality-control step in many
        cryo-electron tomography workflows. Although these artifacts are often
        sparse, their impact on reconstruction quality and downstream analysis
        can be substantial. Careful use of automated cleaning procedures helps
        preserve biologically meaningful signal while reducing detector-related
        distortions that could otherwise complicate structural interpretation.
    """

    _label = 'X-rays eraser'
    _possibleOutputs = {OUTPUT_TILTSERIES_NAME: SetOfTiltSeries}
    stepsExecutionMode = STEPS_PARALLEL

    def __init__(self, **kwargs):
        super().__init__(**kwargs)

    @classmethod
    def worksInStreaming(cls):
        return True

    # -------------------------- DEFINE param functions -----------------------
    def _defineParams(self, form):
        form.addSection(Message.LABEL_INPUT)
        super().addInTsSetFormParam(form)
        form.addParam('peakCriterion',
                      params.FloatParam,
                      default=8.0,
                      label='Peak criterion (in std)',
                      expertLevel=params.LEVEL_ADVANCED,
                      help='Criterion # of SDs above local mean for erasing '
                           'peak based on intensity (the default is 10 SDs)')
        form.addParam('diffCriterion',
                      params.FloatParam,
                      default=6.0,
                      label='Difference criterion  (in std)',
                      expertLevel=params.LEVEL_ADVANCED,
                      help='Criterion # of SDs above mean pixel-to-pixel '
                           'difference for erasing a peak based on '
                           'differences (the default is 8 SDs).')
        form.addParam('maximumRadius',
                      params.FloatParam,
                      default=4.2,
                      label='Maximum radius (px)',
                      expertLevel=params.LEVEL_ADVANCED,
                      help='Maximum radius of peak area to erase (the '
                           'default is 4.2 pixels).')
        form.addParam('bigDiffCriterion',
                      params.IntParam,
                      default=19,
                      label='Big difference criterion  (in std)',
                      expertLevel=params.LEVEL_ADVANCED,
                      help='An extra-large peak will be erased only if the '
                           'value for the maximum difference between '
                           'adjacent pixels, averaged over the most extreme '
                           'one-fourth of the pixels in the patch, '
                           'exceeds this criterion, evaluated as the '
                           'number of SDs above the mean absolute difference '
                           'between adjacent pixels in the scan area. The '
                           'default is 19.  This high a value is needed '
                           'to prevent gold erasure on low-noise data sets '
                           'with small gold particles, and a lower value '
                           'may be needed to make extra-large peak removal '
                           'useful.')
        self.addOddEvenParams(form)
        form.addParallelSection(threads=3, mpi=0)

    # -------------------------- INSERT steps functions -----------------------
    def stepsGeneratorStep(self) -> None:
        self._initialize()
        closeSetStepDeps = []
        inTsSet = self.getInputTsSet()
        outTsSet = getattr(self, OUTPUT_TILTSERIES_NAME, None)
        self.readingOutput(outTsSet)

        while True:
            with self._lock:
                inTsIds = set(inTsSet.getTSIds())

            if not inTsSet.isStreamOpen() and Counter(self.tsIdReadList) == Counter(inTsIds):
                logger.info(cyanStr('Input set closed.\n'))
                self._insertFunctionStep(self.closeOutputSetsStep,
                                         OUTPUT_TILTSERIES_NAME,
                                         prerequisites=closeSetStepDeps,
                                         needsGPU=False)
                break

            nonProcessedTsIds = inTsIds - set(self.tsIdReadList)
            tsToProcessDict = {tsId: ts.clone() for ts in inTsSet.iterItems()
                               if (tsId := ts.getTsId()) in nonProcessedTsIds  # Only not processed tsIds
                               and ts.getSize() > 0}  # Avoid processing empty TS
            for tsId, ts in tsToProcessDict.items():
                cInId = self._insertFunctionStep(self.linkTsStep,
                                                 ts,
                                                 prerequisites=[],
                                                 needsGPU=False)
                compId = self._insertFunctionStep(self.eraseXraysStep,
                                                  ts,
                                                  prerequisites=cInId,
                                                  needsGPU=False)
                outId = self._insertFunctionStep(self.createOutputStep,
                                                 ts,
                                                 prerequisites=compId,
                                                 needsGPU=False)
                closeSetStepDeps.append(outId)
                logger.info(cyanStr(f"Steps created for tsId = {tsId}"))
                self.tsIdReadList.append(tsId)

            self.refreshStreaming(inTsSet)

    # -------------------------- STEPS functions ------------------------------
    def eraseXraysStep(self, ts: TiltSeries):
        tsId = ts.getTsId()
        if tsId not in self.failedItems:
            try:
                logger.info(cyanStr(f'tsId = {tsId} -> Erasing the X-Rays...'))
                firstItem = ts.getFirstEnabledItem()
                inputFile = self.getTmpOutFile(tsId)
                outputFile = self.getExtraOutFile(tsId)
                paramsCcderaser = self.getCcdEraserParamsDict(tsId, inputFile, outputFile)
                self.runProgram(CCDERASER_PROGRAM, paramsCcderaser)
                if self.doOddEven:
                    # Odd
                    logger.info(cyanStr(f'tsId = {tsId} -> Erasing the X-Rays (ODD Tilt-series) ...'))
                    inputFile = firstItem.getOdd()
                    outputFile = self.getExtraOutFile(tsId, suffix=ODD)
                    paramsCcderaser = self.getCcdEraserParamsDict(tsId, inputFile, outputFile)
                    self.runProgram(CCDERASER_PROGRAM, paramsCcderaser)
                    # Even
                    logger.info(cyanStr(f'tsId = {tsId} -> Erasing the X-Rays (EVEN Tilt-series) ...'))
                    inputFile = firstItem.getEven()
                    outputFile = self.getExtraOutFile(tsId, suffix=EVEN)
                    paramsCcderaser = self.getCcdEraserParamsDict(tsId, inputFile, outputFile)
                    self.runProgram(CCDERASER_PROGRAM, paramsCcderaser)
            except Exception as e:
                self.failedItems.append(tsId)
                logger.error(redStr(f'tsId = {tsId} -> {CCDERASER_PROGRAM} execution failed '
                                    f'with the exception -> {e}'))
                logger.error(traceback.format_exc())

    def createOutputStep(self, ts: TiltSeries):
        tsId = ts.getTsId()
        if tsId in self.failedItems:
            self.addToOutFailedSet(ts)
            return
        try:
            outTsFile = self.getExtraOutFile(tsId)
            if not exists(outTsFile):
                logger.error(redStr(f'tsId = {tsId} -> Output file {outTsFile} was not generated. Skipping... '))
                return
            setMRCSamplingRate(outTsFile, ts.getSamplingRate())  # Update the apix value in file header
            self._registerOutput(ts, outTsFile)

        except Exception as e:
            logger.error(redStr(f'tsId = {tsId} -> Unable to register the output with exception {e}. Skipping... '))
            logger.error(traceback.format_exc())

    @retry_on_sqlite_lock(log=logger)
    def _registerOutput(self, ts: TiltSeries, outTsFile: str):
        tsId = ts.getTsId()
        with self._lock:
            # Set of tilt-series
            outTsSet = self.getOutputSetOfTS(self.getInputTsSet(pointer=True))
            # Tilt-series
            outTs = TiltSeries()
            outTs.copyInfo(ts)
            outTsSet.append(outTs)
            # Tilt-images
            for ti in ts.iterItems():
                outTi = TiltImage()
                outTi.copyInfo(ti)
                outTi.setFileName(outTsFile)
                self.setTsOddEven(tsId, outTi, binGenerated=True)
                outTs.append(outTi)
            # Data persistence
            outTs.write()
            outTsSet.update(outTs)
            outTsSet.write()
            self._store(outTsSet)
            # Close explicitly the outputs (for streaming)
            self.closeOutputsForStreaming()

    # --------------------------- UTILS functions -----------------------------
    def getCcdEraserParamsDict(self,
                               tsId: str,
                               inputFile: str,
                               outputFile=str) -> dict:
        return {
            "-InputFile": inputFile,
            "-OutputFile": outputFile,
            "-FindPeaks": 1,
            "-PeakCriterion": self.peakCriterion.get(),
            "-DiffCriterion": self.diffCriterion.get(),
            "-GrowCriterion": 4.,
            "-ScanCriterion": 3.,
            "-MaximumRadius": self.maximumRadius.get(),
            "-GiantCriterion": 12.,
            "-ExtraLargeRadius": 8.,
            "-BigDiffCriterion": self.bigDiffCriterion.get(),
            "-AnnulusWidth": 2.0,
            "-XYScanSize": 100,
            "-EdgeExclusionWidth": 4,
            "-PointModel": self.getExtraOutFile(tsId, suffix="fid", ext=MOD_EXT),
            "-BorderSize": 2,
            "-PolynomialOrder": 2,
        }

    # --------------------------- INFO functions ------------------------------
    def _summary(self):
        summary = []
        output = getattr(self, OUTPUT_TILTSERIES_NAME, None)
        if output is not None:
            summary.append(f"Input tilt-series: {self.getInputTsSet().getSize()}\n"
                           "X-rays erased output tilt series: "
                           f"{output.getSize()}")
        else:
            summary.append("Outputs are not ready yet.")

        return summary

    def _methods(self):
        methods = []
        output = getattr(self, OUTPUT_TILTSERIES_NAME, None)
        if output:
            methods.append(f"The x-rays artifacts have been erased for "
                           f"{output.getSize()} tilt-series using "
                           f"the IMOD *{CCDERASER_PROGRAM}* command.")

        return methods
